USE [master]
GO

/****** Object:  Database [SmarterCityDB]    Script Date: 21/10/2021 1:58:26 AM ******/
CREATE DATABASE [SmarterCityDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SmarterCityDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmarterCityDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SmarterCityDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\SmarterCityDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SmarterCityDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SmarterCityDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SmarterCityDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SmarterCityDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SmarterCityDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SmarterCityDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [SmarterCityDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SmarterCityDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SmarterCityDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SmarterCityDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SmarterCityDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SmarterCityDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SmarterCityDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SmarterCityDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SmarterCityDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SmarterCityDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SmarterCityDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SmarterCityDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SmarterCityDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SmarterCityDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SmarterCityDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SmarterCityDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SmarterCityDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SmarterCityDB] SET RECOVERY FULL 
GO

ALTER DATABASE [SmarterCityDB] SET  MULTI_USER 
GO

ALTER DATABASE [SmarterCityDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SmarterCityDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SmarterCityDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SmarterCityDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SmarterCityDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SmarterCityDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SmarterCityDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SmarterCityDB] SET  READ_WRITE 
GO


USE [SmarterCityDB]
GO

/****** Object:  Table [dbo].[Customers]    Script Date: 21/10/2021 1:59:33 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Customers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](20) NULL,
	[LastName] [nvarchar](20) NULL,
	[MobileNumber] [nvarchar](20) NULL,
	[Address1] [nvarchar](250) NULL,
	[Address2] [nvarchar](250) NULL,
	[Suburb] [nvarchar](50) NULL,
	[State] [nvarchar](3) NULL,
	[PostCode] [nvarchar](4) NULL,
 CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
